# Generated by Django 2.2.16 on 2022-07-09 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20220710_0210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='pics',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text_title',
        ),
    ]
