# Generated by Django 2.2.16 on 2022-07-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_auto_20220712_1724'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='comment',
            name='text_comment',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
