# Generated by Django 2.2.16 on 2022-07-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_auto_20220712_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text_comment',
            field=models.CharField(help_text='Напишите Ваши впечатления после прочтения поста', max_length=200, null=True, verbose_name='Ваш комментарий'),
        ),
    ]
