# Generated by Django 2.2.16 on 2022-07-14 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_auto_20220712_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pics',
            field=models.ImageField(blank=True, help_text='Прикрепите картинку или фотографию', null=True, upload_to='media/', verbose_name='Картинка-волшебница'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text_title',
            field=models.CharField(blank=True, help_text='Привлеките внимание читателей самым важным', max_length=200, null=True, verbose_name='Заголовок'),
        ),
    ]
