# Generated by Django 2.2.16 on 2022-07-17 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_auto_20220718_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Прикрепите картинку или фотографию', null=True, upload_to='posts/', verbose_name='Картинка-волшебница'),
        ),
    ]
